"""
Generates docs/review1_report.md: one dataset taken from raw log lines to
structured events and semantic groups, with a small evaluation against the
dataset's ground-truth labels.

    python scripts/review1_report.py                          # real embedding backend (default config)
    python scripts/review1_report.py --embedding-backend tfidf  # explicit TF-IDF baseline

Everything in the report is computed by running the pipeline; nothing is
typed in by hand. The embedding backend actually used is printed at the top.
Like a research run, it fails if the requested embedding model is unavailable.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import config  # noqa: E402
from src.event_intelligence.cluster_evaluation import mixed_clusters  # noqa: E402
from src.evaluate_clustering import run_evaluation  # noqa: E402
from src.pipeline import load_config_file, run_pipeline  # noqa: E402
from src.preprocessing.datasets import get_dataset  # noqa: E402

DEFAULT_CONFIG = ROOT / "configs" / "loghub_hdfs_2k.json"
OUT = ROOT / "docs" / "review1_report.md"


def _fmt(v, nd=3):
    return "n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v, float) else str(v))


def build_report(cfg: dict) -> str:
    result = run_pipeline(**cfg)
    rep, events, groups = result["report"], result["events"], result["semantic_groups"]
    stages = rep["stages"]
    spec = get_dataset(cfg["dataset"])
    directory = spec.resolve_dir()
    emb, clu = stages["embeddings"], stages["semantic_clustering"]
    ev = clu["evaluation"]
    ext, internal, sizes = ev["external"], ev["internal"], ev["size_distribution"]

    L: list[str] = []
    w = L.append
    w("# Review 1 report: Log Intelligence & Data (Member 1)")
    w("")
    w(f"> Generated by `python scripts/review1_report.py` with embedding backend **{emb['embedding_backend']}**"
      + (f" (`{emb['embedding_model']}`)" if emb["embedding_model"] else " (TF-IDF + SVD baseline, not a sentence-embedding model)")
      + ". Regenerate with the default configuration before presenting if this says TF-IDF.")
    w("")
    w("## 1. What was run")
    w("")
    w(f"- Dataset: **{spec.name}** (`{spec.dataset_id}`), {stages['ingestion']['n_files']} file, "
      f"{stages['parsing']['lines_read']} raw log lines. Details and limitations: `docs/dataset_card.md`.")
    w(f"- Command: `python -m src.pipeline --config configs/loghub_hdfs_2k.json` (mode **{rep['mode']}**, synthetic data: **{rep['is_synthetic']}**).")
    w(f"- LogEvent contract version: `{rep['logevent_schema_version']}` (`docs/interface_contract.md`, `docs/logevent.schema.json`). "
      f"Schema check on the output: {stages['schema_validation']['violations']} violations in {stages['schema_validation']['events_checked']} events.")
    w("")
    w("## 2. Reproducible configuration")
    w("")
    w("| setting | value |")
    w("|---|---|")
    c = rep["config"]
    w(f"| embedding backend / model | {emb['embedding_backend']} / {emb['embedding_model'] or 'none (TF-IDF)'} |")
    w(f"| embedding dimension | {emb['embedding_dimension']} |")
    w(f"| representation (text embedded) | {emb['representation']} |")
    w(f"| clustering | {clu['algorithm']}, distance threshold {clu.get('distance_threshold')}, metric {clu.get('metric')}, linkage {clu.get('linkage')} |")
    w(f"| random seed | {c['seed']} |")
    env = rep["environment"]
    w("| environment | " + ", ".join(f"{k} {v}" for k, v in env.items() if v and k != "platform") + " |")
    w("")
    w("Same configuration + same data + same environment gives byte-identical `events.jsonl`, `embeddings.npy` and `semantic_groups.json` (checked by `tests/test_reproducibility.py` with the TF-IDF backend; confirm it for sentence-transformers on your machine).")
    w("")
    w("## 3. Raw lines to structured events")
    w("")
    p = stages["parsing"]
    w(f"| stage | result |")
    w("|---|---|")
    w(f"| lines read | {p['lines_read']} |")
    w(f"| parsed by a structured parser | {p['parsed']} ({p['formats']}) |")
    w(f"| plain-text fallback | {p['fallback_plain_text']} |")
    w(f"| parser failures (line kept) | {p['failed']} (failure rate {p['parse_failure_rate']}) |")
    n = stages["normalization"]
    w(f"| missing timestamps / unparseable timestamps | {n['missing_timestamps']} / {n['unparseable_timestamps']} |")
    w(f"| severity UNKNOWN after normalization | {n['unresolved_severities']} |")
    w(f"| normalization errors | {n['normalization_errors']} |")
    w(f"| service attributed by dataset config (not in the line) | {n['service_attributed_by_dataset_config']} |")
    x = stages["event_extraction"]
    w(f"| distinct templates mined | {x['n_distinct_templates']} |")
    w("")
    w("### Traceability: one group back to the exact raw lines")
    w("")
    biggest = next(g for g in groups if not g["is_noise"])
    by_id = {e.event_id: e for e in events}
    w(f"Group `{biggest['cluster_id']}` has {biggest['size']} events, representative template `{biggest['representative_template']}`, "
      f"services {biggest['services']}, severities {biggest['severity_distribution']}, "
      f"time span {biggest['time_span']['start']} to {biggest['time_span']['end']}. Three of its members:")
    w("")
    for eid in biggest["event_ids"][:3]:
        e = by_id[eid]
        w(f"- `{eid}` = `{e.source_file}` line {e.line_number}")
        w(f"  - raw: `{e.raw_message}`")
        w(f"  - normalized: `{e.normalized_message}`  |  template: `{e.template}`")
        w(f"  - severity {e.severity} (raw `{e.severity_raw}`), service `{e.service}` (from {e.metadata.get('service_source')}), "
          f"timestamp `{e.timestamp_raw}` to `{e.timestamp_iso}`, parser `{e.parser_name}`, confidence {e.parse_confidence}")
    w("")
    w("## 4. Artifacts (machine-readable)")
    w("")
    out_dir = Path(result["output_dir"])
    for name in config.ARTIFACT_NAMES.values():
        f = out_dir / name
        w(f"- `data/processed/{spec.dataset_id}/{name}`" + (f" ({f.stat().st_size:,} bytes)" if f.exists() else " (missing)"))
    w("")
    w("## 5. Small evaluation of semantic grouping")
    w("")
    w(f"Ground truth: LogHub's per-line `EventId` ({ext['n_ground_truth_classes']} event types). Metrics compare the clusters "
      "with those labels; noise points (none here) would count as one extra group.")
    w("")
    w("| metric | value |")
    w("|---|---|")
    w(f"| clusters found (ground-truth classes) | {clu['n_clusters']} ({ext['n_ground_truth_classes']}) |")
    w(f"| ARI | {_fmt(ext['ari'])} |")
    w(f"| NMI | {_fmt(ext['nmi'])} |")
    w(f"| purity / homogeneity / completeness | {_fmt(ext['purity'])} / {_fmt(ext['homogeneity'])} / {_fmt(ext['completeness'])} |")
    w(f"| silhouette (cosine) / Davies-Bouldin | {_fmt(internal['silhouette_cosine'])} / {_fmt(internal['davies_bouldin'])} |")
    w(f"| noise fraction | {sizes['noise_fraction']} |")
    w(f"| cluster sizes (largest 8) | {sizes['sizes'][:8]} |")
    w("")
    truth = spec.ground_truth_loader(directory)
    y = [truth[(e.source_file, e.line_number)] for e in events]
    labels = [e.semantic_cluster for e in events]
    mixed = mixed_clusters(labels, y)
    w("Clusters that mix ground-truth classes (where the grouping disagrees with the labels): "
      + ("none." if not mixed else "; ".join(f"cluster {m['cluster_id']} ({m['size']} events): {m['truth_classes']}" for m in mixed)))
    w("")
    w("### Does the choice of embedded text matter?")
    w("")
    w("Same dataset, same clustering threshold, all 2,000 events; only the embedded text changes.")
    w("")
    w("| representation | clusters | ARI | NMI | silhouette |")
    w("|---|---|---|---|---|")
    backend = cfg.get("embedding_backend")
    comp = run_evaluation(spec.dataset_id, split="all", embedding_backend=backend,
                          grid=[{"algorithm": cfg.get("algorithm", config.CLUSTERING_ALGORITHM),
                                 **cfg.get("clustering_params", {})}], seed=cfg.get("seed"))
    for r in comp["rows"]:
        e2 = r["evaluation"]
        w(f"| {r['embedding']['representation']} | {r['clustering']['n_clusters']} | {_fmt(e2['external']['ari'])} | "
          f"{_fmt(e2['external']['nmi'])} | {_fmt(e2['internal']['silhouette_cosine'])} |")
    w("")
    w("### Tune / held-out halves for the chosen configuration")
    w("")
    w("| split | events | clusters | ARI | NMI |")
    w("|---|---|---|---|---|")
    for split in ("tune", "heldout"):
        r = run_evaluation(spec.dataset_id, split=split, embedding_backend=backend, representations=[emb["representation"]],
                           grid=[{"algorithm": cfg.get("algorithm", config.CLUSTERING_ALGORITHM),
                                  **cfg.get("clustering_params", {})}], seed=cfg.get("seed"))
        row = r["rows"][0]
        w(f"| {split} | {r['n_events']} | {row['clustering']['n_clusters']} | "
          f"{_fmt(row['evaluation']['external']['ari'])} | {_fmt(row['evaluation']['external']['nmi'])} |")
    w("")
    w("### Mined templates vs ground-truth event types")
    w("")
    templ = {}
    with open(directory / "HDFS_2k.log_templates.csv", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            templ[row["EventId"]] = row["EventTemplate"]
    mined = defaultdict(set)
    count = Counter(y)
    for e, cls in zip(events, y):
        mined[cls].add(e.template)
    w("| ground-truth id | events | mined templates | LogHub template |")
    w("|---|---|---|---|")
    for cls, n_ev in count.most_common():
        w(f"| {cls} | {n_ev} | {len(mined[cls])} | `{templ.get(cls, '?')}` |")
    w("")
    n_split = sum(1 for cls in count if len(mined[cls]) > 1)
    n_split_nominus = sum(1 for cls in count if len({t.replace("blk_-<NUM>", "blk_<NUM>") for t in mined[cls]}) > 1)
    w(f"The masking step yields {x['n_distinct_templates']} templates for {len(count)} true event types; {n_split} of the "
      f"{len(count)} types are split into more than one template. Most of that comes from the minus sign of a negative block id being "
      f"left outside the number mask (`blk_-<NUM>` vs `blk_<NUM>`): treating the two alike leaves {n_split_nominus} split type(s). "
      "The clustering step puts split pairs back together; where it merges different true types instead, they are listed under "
      "\"Clusters that mix ground-truth classes\" above. This is a known limitation (`docs/dataset_card.md`).")
    w("")
    w("## 6. What this does and does not show")
    w("")
    w("- Shows: one dataset, 2,000 real raw lines, turned into validated structured events and semantic groups, with every step "
      "configured, seeded and saved as files, and every group traceable to exact raw lines.")
    w("- Shows: how well events are grouped by log meaning *on this dataset*, measured against LogHub's template labels.")
    w("- **Does not show** that the system can identify root causes. HDFS_2k has no root-cause or anomaly labels, and good "
      "semantic grouping does not by itself demonstrate root-cause identification.")
    w("- Does not show that the method generalizes: this dataset has 14 near-deterministic event types, one service, no hosts and only "
      "INFO/WARN lines, and the grouping is nearly perfect with template embeddings. Harder datasets are needed before comparing methods.")
    w("")
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--embedding-backend", choices=["sentence-transformers", "tfidf"], default=None)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args(argv)
    cfg = load_config_file(args.config)
    if args.embedding_backend:
        cfg["embedding_backend"] = args.embedding_backend
    text = build_report(cfg)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
